### ISSUE TITLE
Gamebreaking Bug

### ISSUE THREAD

**Issue by Jonas01234500** [lukcod3/roleplaygame#4]
Wenn das Einhorn am Rand der Map ist und man gegen die Wand laufen will und dabei noch in eine andere Richtung läuft man garnicht. Bsp: Man ist am unteren Rand der Map, drückt s und d, man sollte dann nach rechts laufen, läuft aber gar nicht

**Comment by lukcod3** [comment]
fixed (97addfffbbc44b2333eae4fd7149bb388c0350e2)
