### ISSUE TITLE
hit animation "bug"

### ISSUE THREAD

**Issue by Tim-17** [lukcod3/roleplaygame#8]
Ich weiß nicht, wie ich es umsetzen kann, dass der Benutzer nur alle (beispielsweise) 100 Millisekunden oder so schlagen kann, also dass es ein Zeitlimit gibt, sodass man nicht die ganze Zeit schlagen kann, sondern immer 'n bisschen warten muss.
Kann mir jemand helfen?

**Comment by lukcod3** [comment]
Ich würde ein Zeit-Attribut beim Player einfügen auf das (nach einem Schlag) bei jedem Update die vergangene Zeit addiert wird. Ist ein bestimmer Threshold erreicht wird keine Zeit mehr addiert und bei einem Versuch des Nutzers zu schlagen wird eben mit diesem Threshold überprüft ob er dazu berechtigt ist. Falls ja wird die Aktion ausgeführt und das Attribut zurückgesetzt.
