### ISSUE TITLE
player width

### ISSUE THREAD

**Issue by Tim-17** [lukcod3/roleplaygame#9]
Der Held wird in "engen" 1 Tile breiten Gängen nicht mittig angezeigt, sondern rechts und mann kann die Gänge auch nur rechts betreten.

**Comment by lukcod3** [comment]
Fixed (5551bf0ec7b7dd396fc73383f14991ef9e010b14). Die tatsächlich gezeichnenten Grafiken entsprechen aus grafischen Gründen nicht den virtuellen Werten mit denen die Kollisionen berechnet werden. In Extremfällen könnte die gezeichnete Figur des Spielers größer als dessen Hitbox sein, was zur Verwirrung führt, aber momentan gibt es keine andere Lösung.
